matrix:
  include:
    - language: python
      python: 3.8.5
      install: 
        - "pip install --upgrade pip"
        - "pip install pipenv"
        - "pipenv install --dev"
        - "pip install codecov"
      script:
        - pytest --cov=app --cov-report=xml
      after_success:
        - codecov

    - language: node_js
      node_js:
        - 12.18.4
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
        - export PATH="$HOME/.yarn/bin:$PATH"
        - yarn install
        - yarn build
branches:
  only:
  - master
  - dev/main
git:
  depth: 2